/**
 * Store global settings (CONFIG)
 */
export default {
    APP_VERSION: APP_VERSION,
    APP_PACKAGE_VERSION: APP_PACKAGE_VERSION,
    __ELECTRON__: __ELECTRON__,
    CORE_ASSET: CORE_ASSET,
    CORE_ASSET_ID: CORE_ASSET_ID,
    FAUCET_URLS: FAUCET_URLS,
    BLOCKCHAIN_URL: BLOCKCHAIN_URL,
};